### ISSUE TITLE
No way to pass challenge in proof request, v3 not working with challenge

### ISSUE THREAD

**Issue by sirpy** [0xPolygonID/js-sdk#182]
It seems like the challenge should be actually taken from proofReq.params.challenge, otherwise there doesnt seem to be a way to pass to challenge
https://github.com/0xPolygonID/js-sdk/blob/21159ba3ce59a80c7f504cd269f02cfa379618fd/src/proof/inputs-generator.ts#L281

when changing it, then the js-sdk-examples seems to generate proof for       `circuitId: CircuitId.AtomicQueryMTPV2OnChain`

but for `AtomicQueryV3OnChain` after adding a challenge there's an error thrown in witness calculation

```
Error: Error: Assert Failed.
Error in template ForceEqualIfEnabled_4 line: 56
Error in template SMTVerifier_234 line: 134
Error in template checkClaimExists_235 line: 19
Error in template verifyClaimIssuance_444 line: 89
Error in template credentialAtomicQueryV3OffChain_472 line: 168
Error in template credentialAtomicQueryV3OnChain_550 line: 204

    at /Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:143:27
    at Array.forEach (<anonymous>)
    at WitnessCalculator._doCalculateWitness (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:117:14)
    at WitnessCalculator.calculateWTNSBin (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:180:20)
```

**Comment by vmidyllic** [comment]
CredentialAtomicQueryV3OnChain-beta.0 circuit supports challenge as paramer from request.   https://github.com/0xPolygonID/js-sdk/blob/21159ba3ce59a80c7f504cd269f02cfa379618fd/src/proof/inputs-generator.ts#L530

**Comment by sirpy** [comment]
@vmidyllic 
There's no way to pass params.challenge, because the params field value in the input generator doesnt include the params passed in the proof request.
You can see that for the `nullifier` value it correctly takes it from `proofReq.params`.

If you follow the code on js-sdk-examples
https://github.com/0xPolygonID/js-sdk-examples/blob/f248649c09c862f0a0539abd2f0b54cd394ad7bb/index.ts#L986

Try to add `params: { challenge: 1 }` and modify the circuit to `circuitId: CircuitId.AtomicQueryMTPV2OnChain` and you will see the error regarding the missing challenge.

If you modify the code to read the challenge from params.proofReq the js-sdk-example works correctly for MTPV2OnChain
but for V3 it doesnt.

This proof request works (after reading challenge from proofReq):
It also works with PRoofType.BJJSignature
``const proofReqs: ZeroKnowledgeProofRequest[] = [
    {
      id: 1,
      circuitId: CircuitId.AtomicQueryMTPV2OnChain,
      optional: false,
      params: {
        challenge: ethSigner.address
      },
      query: {
        allowedIssuers: [issuerDID.string()],
        type: claimReq.type,
        proofType: ProofType.Iden3SparseMerkleTreeProof,
        context:
          'https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-nonmerklized.jsonld',
        credentialSubject: {
          documentType: {
            $eq: 99
          }
        }
      }
    }]
```
Changing circuit id to `AtomicQueryV3OnChain` then fails with the witness error. Also changing the proof type to BJJSignature still fails with AtomicQueryV3OnChain

I followed the stack calls and there's simply no way to pass values to `params`
````
Error: empty challenge
    at AtomicQueryV3OnChainInputs.validate (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/circuits/atomic-query-v3-on-chain.js:33:19)
    at AtomicQueryV3OnChainInputs.inputsMarshal (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/circuits/atomic-query-v3-on-chain.js:110:14)
    at InputGenerator.credentialAtomicQueryV3OnChainPrepareInputs (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/inputs-generator.js:284:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProofService.generateProof (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/proof-service.js:95:24)
    at async AuthHandler.handleAuthorizationRequest (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/iden3comm/handlers/auth.js:153:28)
    at async handleAuthRequestV3CircuitsBetaStateTransition (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/index.ts:993:30)
    at async main (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/index.ts:1038:7)
    at async /Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/index.ts:1068:3
````

**Comment by vmidyllic** [comment]
@sirpy for onchain circuits you should use the Contract Request Invoke handler. 
https://github.com/0xPolygonID/js-sdk/blob/main/src/iden3comm/handlers/contract-request.ts

to generate proof for onchain circuits  if you do not need to send tx to blockchain, please use next function. 

https://github.com/0xPolygonID/js-sdk/blob/36ddc67f998e1032ab543f1135cd307a63d74809/src/proof/proof-service.ts#L226

**Comment by vmidyllic** [comment]
To generate proof for onchain circuits you need to use Contract  Request handler 
https://github.com/0xPolygonID/js-sdk/blob/main/src/iden3comm/handlers/contract-request.ts

To understand which handler to use you can rely on type field. 
https://iden3-communication.io/proofs/1.0/contract-invoke-request/

To generate zkp for circuits if you don't need to send tx to blockchain, please use generateProof function
https://github.com/0xPolygonID/js-sdk/blob/36ddc67f998e1032ab543f1135cd307a63d74809/src/proof/proof-service.ts#L226

We will add handler chain functionality in the future releases. 

There is no explicit challenge in auth repsponse handler for now.

**Comment by sirpy** [comment]
@vmidyllic if you look at the stack trace it already uses the proof service, I think there's still a bug here that it doesn't pass the challenge correctly

**Comment by sirpy** [comment]
@vmidyllic @Kolezhniuk 
This issue should be re-opened.
the js-sdk already uses generateProof the only contract-request does differently is passing the challenge correctly.
In my tests i've already fixed the challenge passing, once you pass the challenge correctly then there's the circuit bug i've reported.
If you pass challenge correctly then a proof is generated correctly for V2 requests such as `AtomicQueryMTPV2OnChain`
But throws the error i've reported if you request `AtomicQueryV3OnChain`
